/**
 * The given name a creature is born with, and keeps forever.
 *
 * Roster §3: the given name comes from the alien-word generator "seeded
 * deterministically from `species + set`, so every child's blue-set hedgehog is
 * the same Bimo, forever". That is not a convenience — it is the whole point.
 * Two children in a playground comparing islands have to be able to say "have
 * you got Bimo?" and mean the same animal. A name that varies per save is a
 * name that cannot be talked about.
 *
 * So names are generated ONCE, AUDITED by Joe (`joe/names-audit.json`), and
 * then FROZEN AS DATA. Nothing here is regenerated at runtime for a creature a
 * child already owns — see the §19 test in `tests/island/naming.test.ts`.
 *
 * ## Why the band filter lives here and not in the generator
 *
 * Roster §3 also wants "name difficulty rides collection order": early
 * collections draw short CVC-ish names, later ones may draw longer ones. The
 * obvious implementation is a length argument on `petName`. We do not do that.
 * `src/core/names.ts` sits inside `src/core/`, which `npm run parity` guards
 * and which `tools/golden/golden.json` pins byte-for-byte; a signature change
 * there risks both gates for a feature that belongs to the island layer
 * anyway. Instead we FILTER the seeded output: draw from the untouched
 * generator until the result's length falls inside the collection's band
 * (`NAME_BANDS`, types.ts:246). Every band is a subrange of the generator's own
 * 5–9, so no band is unreachable, and `src/core/` is not touched at all.
 *
 * ## Why the names are ALLOCATED and not merely drawn
 *
 * A per-species seed makes each draw independent, and independent draws collide
 * — that is the birthday problem, not bad luck. At 320 species one collision was
 * already real: `Gichesh` was drawn for both the warthog and the otter. A shared
 * name is not a cosmetic blemish here, it is the failure of the whole feature.
 * Roster §3 makes the given name "playground currency": two children comparing
 * islands say "have you got Gichesh?" and must mean ONE creature. A name that
 * names two animals is not currency, it is noise.
 *
 * So naming is an ALLOCATION over the whole roster, not a lookup per species.
 * `_allocate` walks all 320 species in roster order and hands each one the first
 * name off its own seeded stream that is both in-band and NOT ALREADY TAKEN.
 * Deterministic, reproducible, pure, and — the point — collision-free by
 * construction rather than by luck.
 *
 * THE ALLOCATION SET IS THE FULL RATIFIED ROSTER, NOT THE BUILT SPECIES. That is
 * the load-bearing choice. All 320 are named whether or not a kit exists to
 * build them, so finishing the songbird kit, or the swim kit, or the last
 * bespoke one-off, cannot rename a single creature. If allocation ran over only
 * what was built, every new kit would reshuffle the names of animals children
 * already own, which is brief §19 with extra steps. The roster is ratified data;
 * the build queue is not, so the roster is what we allocate over.
 *
 * Consequences worth knowing before you edit this:
 *   - Only the LOSER of a collision moves — the species that comes later in
 *     roster order. Fixing `Gichesh` renamed the otter (Woodland, collection 9)
 *     and left the warthog (Africa, collection 4) exactly where it was. All 318
 *     other names are byte-identical to the pre-allocation draw, and
 *     `tests/island/naming.test.ts` proves that species by species.
 *   - EDITING `COLLECTIONS` ORDER, OR INSERTING A SPECIES MID-ROSTER, CAN
 *     RENAME CREATURES that come after the edit. Appending is safe; inserting is
 *     not. If the roster must be reordered, pin the old names first.
 *   - A pin wins everywhere and is reserved before any draw, so pinning is
 *     order-independent. A pin renames somebody else only if the pinned STRING
 *     is a name already allocated elsewhere — never merely by freeing the name
 *     its own species would otherwise have drawn.
 *
 * ## What is NOT here, deliberately
 *
 * There is no rename migration. Joe, 29 July: *"i will give you juno's already
 * achieved animal's names as her latest save game later, you can swap the first
 * hard code out after."* The child's existing pets' names become the canonical
 * names for their `species + set` by being PINNED as data below — not by code
 * walking a save and rewriting it. A stored `Pet.name` is never read, rewritten
 * or regenerated by this module, and `Pet.id` embeds the name (`flow.ts:327`),
 * so touching one would break an id too.
 *
 * The live hatch path (`main.ts:1174`) still calls `petName(defaultRng)` —
 * unseeded. Swapping that to `givenName()` is a ONE-LINE change, and it waits
 * on the audit, because the brief's own order is: generate, audit, then ship.
 */
import { petName } from '../../core/names'
import { mulberry32 } from '../../core/rng'
import { COLLECTIONS, collectionOf } from './roster'
import { NAME_BANDS } from './types'
import type { NameBand } from './types'
import pinFile from './name-pins.json'

/**
 * >>> PROVISIONAL — the pin table is EMPTY ON PURPOSE.
 *
 * `src/island/species/name-pins.json` ships with `{"schemaVersion": 1,
 * "pins": {}}` and not one invented entry. Juno already has animals on the
 * island with names they know. When Joe supplies that save, THEIR names go in
 * this file, keyed `${setId}/${speciesId}` — and that is precisely what "you
 * can swap the first hard code out after" means. Nothing else in the codebase
 * changes when they land: no migration runs, no save is rewritten, no id moves.
 * A pin simply wins over the generated draw from then on, for every island.
 *
 * Guessing a name into this file would invent a memory Juno does not have, so
 * INVENT NOTHING. `tests/island/naming.test.ts` asserts the table is empty; that
 * assertion is a deliberate tripwire and is meant to be deleted or inverted the
 * day that save arrives.
 * <<<
 */
export const NAME_PINS: Readonly<Record<string, string>> =
  (pinFile as { pins?: Record<string, string> }).pins ?? {}

/**
 * The one set every creature is named in. JT-029.
 *
 * Joe ruled on 29 July: *"we drop the colours, only the sets in their natural
 * color. we may add silver and gold later if we run low and we can just add
 * something like 'the great' to their original name."* So a given name is keyed
 * on SPECIES ALONE — 320 names at the full roster, not the 8,000 that
 * `species + set` implied, and every one of those 320 is a name he has to audit
 * by hand and bake in Olivia's voice. That factor of twenty-five was the whole
 * reason JT-029 was raised.
 *
 * WHY THE `natural/` PREFIX SURVIVES IN THE HASHED KEY. Two reasons, and
 * neither is inertia:
 *   1. Removing it changes every seed, which renames the fourteen creatures
 *      already sitting in `joe/names-audit.json` waiting for Joe's eyes. They
 *      have no verdicts on them yet so nothing would be *lost* — but renaming
 *      them buys precisely nothing, and the habit of not renaming creatures is
 *      the habit this module exists to keep.
 *   2. He explicitly left the door open to a silver and gold tier. Should that
 *      land, its name is the ORIGINAL name decorated ("the great"), not a fresh
 *      draw — so the key shape stays able to carry a set without the naming
 *      path ever again multiplying species by sets.
 *
 * The set is therefore a CONSTANT here, not a parameter. It used to be an
 * argument, and an argument is an invitation to pass a real set id and quietly
 * recreate the 8,000 names Joe just ruled out.
 */
export const NATURAL_SET = 'natural'

/**
 * The stable 32-bit seed for one creature's name. FNV-1a over
 * `` `${NATURAL_SET}/${speciesId}` ``.
 *
 * The hashed string is deliberately the SAME shape as `variantKey`
 * (`variants/sets.ts:168`) and the same shape `collection.ts:43-50` says the
 * deck will one day deal, so there is exactly one spelling of "which creature
 * is this" in the codebase.
 *
 * FNV-1a because it is four lines, has no platform-dependent behaviour, and
 * `Math.imul` keeps the multiply exactly 32-bit on every engine. No `hashCode`
 * off a library, no `charCodeAt` sum that collides on anagrams.
 *
 * CHANGING THIS FUNCTION RENAMES EVERY CREATURE IN THE GAME. Brief §19 forbids
 * losing a child's friend, and a friend whose name changed is lost even though
 * the record survived. If a better hash is ever wanted, the answer is not to
 * edit this — it is to pin the old names first.
 */
export function nameSeed(speciesId: string): number {
  const key = `${NATURAL_SET}/${speciesId}`
  let h = 0x811c9dc5
  for (let i = 0; i < key.length; i++) {
    h ^= key.charCodeAt(i)
    h = Math.imul(h, 0x01000193)
  }
  return h >>> 0
}

/**
 * How many redraws the band filter is allowed before it gives up.
 *
 * The generator makes 5–9 letter names and the narrowest band takes two of
 * those five lengths, so a hit is common and this cap is never approached in
 * practice — it exists so a future band (or a future generator) can never spin
 * this function forever. On exhaustion we return the FIRST draw rather than
 * throwing: a child must always get a name, and a name one letter outside its
 * band is a reading exercise slightly off target, while a crash at the hatch is
 * the emotional peak of the game replaced by an error. Survivable beats
 * correct here.
 */
const MAX_REDRAWS = 200

/** The band a species' names are drawn from; `medium` for an unknown species. */
export function nameBandOf(speciesId: string): NameBand {
  return collectionOf(speciesId)?.band ?? 'medium'
}

/**
 * Every species the roster knows, in the one canonical order: `COLLECTIONS` in
 * declaration order, each collection's `members` in declaration order. 320 of
 * them, base 24 first.
 *
 * This order IS the allocation priority. It is not ship order and must not be
 * quietly swapped for one: ship order is a product decision that can change,
 * and a name that changes when a ship order changes is not frozen at all.
 */
const ROSTER_ORDER: readonly string[] = COLLECTIONS.flatMap((c) => c.members)

/**
 * One species' name, drawn off its own seeded stream, skipping anything already
 * spoken for.
 *
 * Preference order, and each fallback is deliberate:
 *   1. free AND in band — what happens 320 times out of 320 today;
 *   2. free but out of band — a name one letter off target is a reading
 *      exercise slightly misaimed;
 *   3. the very first draw, band and collisions be damned — because a child
 *      must always get a name. A duplicate is survivable; a crash at the hatch
 *      replaces the emotional peak of the game with an error.
 * `MAX_REDRAWS` exists so a future band, or a future generator, can never spin
 * this forever. With ~647,000 reachable names and 320 taken, it is never
 * approached.
 */
function draw(
  speciesId: string, band: { min: number; max: number }, taken: ReadonlySet<string>,
): string {
  const rng = mulberry32(nameSeed(speciesId))
  let first = ''
  let firstFree = ''
  for (let i = 0; i < MAX_REDRAWS; i++) {
    const w = petName(rng)
    if (i === 0) first = w
    if (taken.has(w)) continue
    if (w.length >= band.min && w.length <= band.max) return w
    if (firstFree === '') firstFree = w
  }
  return firstFree !== '' ? firstFree : first
}

/**
 * The whole naming table, computed in one pass over the roster.
 *
 * Two passes, and the order of the two is the rule:
 *   1. **Pins are reserved first, all of them.** A pin is a name a child
 *      already says out loud; it outranks the band, and it outranks any
 *      generated draw no matter where either sits in roster order. Reserving
 *      them up front is what makes pinning order-independent — a pin on the
 *      last species in the roster wins against the first just as surely.
 *   2. **Then every unpinned species draws, in roster order**, taking the first
 *      name off its own stream that nobody holds.
 *
 * Pure: same roster + same pins in, same table out, on every machine and every
 * run. `givenName` memoises the `NAME_PINS` call of this; tests pass their own
 * table and pay the (trivial) recompute.
 */
export function _allocate(
  pins: Readonly<Record<string, string>>,
): Readonly<Record<string, string>> {
  const out: Record<string, string> = {}
  const taken = new Set<string>()

  for (const id of ROSTER_ORDER) {
    const pinned = pins[`${NATURAL_SET}/${id}`]
    if (pinned === undefined) continue
    out[id] = pinned
    taken.add(pinned)
  }

  for (const id of ROSTER_ORDER) {
    if (out[id] !== undefined) continue
    const name = draw(id, NAME_BANDS[nameBandOf(id)], taken)
    out[id] = name
    taken.add(name)
  }

  return out
}

/** The `NAME_PINS` allocation, computed once. 320 draws is cheap, but not free. */
let memo: Readonly<Record<string, string>> | undefined

/**
 * The resolution order, with an injectable pin table so tests need not touch
 * the JSON. `givenName` is this, called with `NAME_PINS`.
 *
 *   1. A pin for `${NATURAL_SET}/${speciesId}` wins outright — including over
 *      the band, because a pin is a name a child already says out loud and no
 *      length rule outranks that.
 *   2. Otherwise the species takes its slot in the roster-wide allocation.
 *   3. A species the roster has never heard of — a save from a future build —
 *      still gets a name, drawn off its own seed and steered clear of every
 *      allocated name so it cannot arrive already colliding.
 *
 * The identity check against `NAME_PINS` is how the memo is reached without
 * making the pin table a hidden global on the hot path; a test's own table
 * recomputes, which at 320 draws costs nothing anybody can measure.
 */
export function _resolve(
  pins: Readonly<Record<string, string>>, speciesId: string,
): string {
  const pinned = pins[`${NATURAL_SET}/${speciesId}`]
  if (pinned !== undefined) return pinned

  const table = pins === NAME_PINS ? (memo ??= _allocate(NAME_PINS)) : _allocate(pins)
  const allocated = table[speciesId]
  if (allocated !== undefined) return allocated

  return draw(
    speciesId, NAME_BANDS[nameBandOf(speciesId)], new Set(Object.values(table)),
  )
}

/**
 * The frozen given name for one species. JT-029: one name per species, not one
 * per species and set.
 *
 * An unknown species — one from a build newer than this roster — still gets a
 * name, off the `medium` band. `script.ts:132 speciesName()` sets that
 * precedent: a save from a future build must never leave a blank where a
 * child's friend's name goes.
 *
 * NOTE FOR WHOEVER WIRES THE HATCH. The phase 1 handoff told you to call this
 * as `givenName(species, setId)` and to take the set id from wherever the
 * variant engine picks it. That instruction is now WRONG — JT-029 removed the
 * second argument. Call `givenName(species)` and pass no set at all.
 */
export function givenName(speciesId: string): string {
  return _resolve(NAME_PINS, speciesId)
}
