/**
 * Every species the assembly kit can build — one line each, and nothing else.
 *
 * This was one 562-line file holding two species' records. Thirteen Garden
 * species are now being built in parallel and that file was the most
 * comment-dense in the repo: every number in an `AssemblyBuild` carries the
 * measurement that produced it, in a comment beside it, and a comment lost in a
 * merge is a reason lost with nothing left to show it was ever there.
 *
 * So the records live one per file under this directory, named for the species
 * id, and this file is the whole of the shared surface.
 *
 * ## ADDING A SPECIES IS A FILE AND A LINE
 *
 *   1. Write `parts/assembled/animal-<name>.ts`. It exports one const, defined
 *      through `defineAssembly('animal-<name>', { ... })`.
 *   2. APPEND one `export { ... } from './animal-<name>'` line to the list below.
 *
 * Nothing else. Not `parts/index.ts` (it re-exports this whole module with a
 * `export *`), not `collections/garden.ts` (`defineSpecies` picks the assembly up
 * by id off the register), not `assembledSpecies()`, not `buildAssembled()`.
 *
 * **Why one line is enough.** Evaluating a re-export evaluates the module it
 * names, and a species module calls `defineAssembly` as it defines its const —
 * so the same line that publishes the name is what puts the species on the
 * register that `ASSEMBLED_BUILDS` and `assemblyFor` read. See `register.ts`.
 *
 * ## THE LINE MUST NEVER PRECEDE THE FILE
 *
 * Step 1 then step 2, always, and never the other way round. On 29 July a
 * manager fanning out eleven species in parallel wrote all thirteen lines here
 * UP FRONT, so the subagents would not have to touch a shared file. Five of the
 * files did not exist yet, the module graph failed to resolve, and the viewer
 * went blank — for Joe, live, because the workbench dev server reads this
 * working tree directly. There is no "it is fine once I commit".
 *
 * So with concurrent subagents the rule is: **each appends its own line only
 * after its file is written and type-checks, or the manager appends centrally
 * as each subagent REPORTS.** A subagent is finished when it has reported, not
 * when it was dispatched. If a batch genuinely cannot keep the tree loadable at
 * every instant, do it in a worktree and merge it in complete.
 *
 * **APPEND, do not sort.** The list order is the order `assembledSpecies()`
 * reports and the order the approver bench shows. §6 of
 * `docs/building-animals-from-parts.md` is one species at a time, in the order
 * they shipped, and the hedgehog is first because it was first.
 *
 * §0 still holds over all of it: the names and the facts are never regenerated,
 * and a species that is not in the roster throws rather than being invented.
 */
export { HEDGEHOG_ASSEMBLY } from './animal-hedgehog'
export { SQUIRREL_ASSEMBLY } from './animal-squirrel'
export { MOUSE_ASSEMBLY } from './animal-mouse'
export { SHREW_ASSEMBLY } from './animal-shrew'
export { DORMOUSE_ASSEMBLY } from './animal-dormouse'
export { VOLE_ASSEMBLY } from './animal-vole'
export { FROG_ASSEMBLY } from './animal-frog'
export { TOAD_ASSEMBLY } from './animal-toad'
export { TORTOISE_ASSEMBLY } from './animal-tortoise'
export { SALAMANDER_ASSEMBLY } from './animal-salamander'
export { NEWT_ASSEMBLY } from './animal-newt'
export { BADGER_ASSEMBLY } from './animal-badger'
export { MOLE_ASSEMBLY } from './animal-mole'
export { SLOW_WORM_ASSEMBLY } from './animal-slow-worm'
export { CORN_SNAKE_ASSEMBLY } from './animal-corn-snake'
export { GOLDFISH_ASSEMBLY } from './animal-goldfish'
export { CROCODILE_ASSEMBLY } from './animal-crocodile'
export { OPOSSUM_ASSEMBLY } from './animal-opossum'
export { NIGHTJAR_ASSEMBLY } from './animal-nightjar'
export { WOLF_ASSEMBLY } from './animal-wolf'
export { TARSIER_ASSEMBLY } from './animal-tarsier'
export { FIREFLY_ASSEMBLY } from './animal-firefly'
export { CIVET_ASSEMBLY } from './animal-civet'
export { KINKAJOU_ASSEMBLY } from './animal-kinkajou'
export { RACCOON_ASSEMBLY } from './animal-raccoon'
export { KIWI_ASSEMBLY } from './animal-kiwi'
export { BUSHBABY_ASSEMBLY } from './animal-bushbaby'
export { FENNEC_FOX_ASSEMBLY } from './animal-fennec-fox'
export { AYE_AYE_ASSEMBLY } from './animal-aye-aye'
export { GLOW_WORM_ASSEMBLY } from './animal-glow-worm'
export { CHINCHILLA_ASSEMBLY } from './animal-chinchilla'
export { GUINEA_PIG_ASSEMBLY } from './animal-guinea-pig'
export { PONY_ASSEMBLY } from './animal-pony'
export { HAMSTER_ASSEMBLY } from './animal-hamster'
export { DEGU_ASSEMBLY } from './animal-degu'
export { GECKO_ASSEMBLY } from './animal-gecko'
export { GERBIL_ASSEMBLY } from './animal-gerbil'
export { FERRET_ASSEMBLY } from './animal-ferret'
export { BUDGIE_ASSEMBLY } from './animal-budgie'
export { RAT_ASSEMBLY } from './animal-rat'
export { TERRAPIN_ASSEMBLY } from './animal-terrapin'
export { COCKATIEL_ASSEMBLY } from './animal-cockatiel'
export { LOVEBIRD_ASSEMBLY } from './animal-lovebird'
export { CANARY_ASSEMBLY } from './animal-canary'
export { CHICKEN_ASSEMBLY } from './animal-chicken'
export { SHEEP_ASSEMBLY } from './animal-sheep'
export { HORSE_ASSEMBLY } from './animal-horse'
export { GOOSE_ASSEMBLY } from './animal-goose'
export { MULE_ASSEMBLY } from './animal-mule'
export { ALPACA_ASSEMBLY } from './animal-alpaca'
export { ROOSTER_ASSEMBLY } from './animal-rooster'
export { PIGEON_ASSEMBLY } from './animal-pigeon'
export { OX_ASSEMBLY } from './animal-ox'
export { LLAMA_ASSEMBLY } from './animal-llama'
export { QUAIL_ASSEMBLY } from './animal-quail'
export { GUINEA_FOWL_ASSEMBLY } from './animal-guinea-fowl'
export { TURKEY_ASSEMBLY } from './animal-turkey'
export { DONKEY_ASSEMBLY } from './animal-donkey'
export { GOAT_ASSEMBLY } from './animal-goat'
export { WATER_BUFFALO_ASSEMBLY } from './animal-water-buffalo'
export { HARE_ASSEMBLY } from './animal-hare'
export { STOAT_ASSEMBLY } from './animal-stoat'
export { CHIPMUNK_ASSEMBLY } from './animal-chipmunk'
export { BEAR_ASSEMBLY } from './animal-bear'
export { OTTER_ASSEMBLY } from './animal-otter'
export { ELK_ASSEMBLY } from './animal-elk'
export { PINE_MARTEN_ASSEMBLY } from './animal-pine-marten'
export { LYNX_ASSEMBLY } from './animal-lynx'
export { SKUNK_ASSEMBLY } from './animal-skunk'
export { PORCUPINE_ASSEMBLY } from './animal-porcupine'
export { WOLVERINE_ASSEMBLY } from './animal-wolverine'
export { WILDCAT_ASSEMBLY } from './animal-wildcat'
export { PHEASANT_ASSEMBLY } from './animal-pheasant'
export { CAPERCAILLIE_ASSEMBLY } from './animal-capercaillie'
export { MINK_ASSEMBLY } from './animal-mink'
export { COYPU_ASSEMBLY } from './animal-coypu'
export { ROBIN_ASSEMBLY } from './animal-robin'
export { BLUE_TIT_ASSEMBLY } from './animal-blue-tit'
export { MAGPIE_ASSEMBLY } from './animal-magpie'
export { WREN_ASSEMBLY } from './animal-wren'
export { BLACKBIRD_ASSEMBLY } from './animal-blackbird'
export { OWLET_ASSEMBLY } from './animal-owlet'
export { SEAGULL_ASSEMBLY } from './animal-seagull'
export { WOODPECKER_ASSEMBLY } from './animal-woodpecker'
export { KINGFISHER_ASSEMBLY } from './animal-kingfisher'
export { DUCK_ASSEMBLY } from './animal-duck'
export { PUFFIN_ASSEMBLY } from './animal-puffin'
export { SHARK_ASSEMBLY } from './animal-shark'
export { PUFFERFISH_ASSEMBLY } from './animal-pufferfish'
export { OCTOPUS_ASSEMBLY } from './animal-octopus'
export { TURTLE_ASSEMBLY } from './animal-turtle'
export { WHALE_ASSEMBLY } from './animal-whale'
export { DOLPHIN_ASSEMBLY } from './animal-dolphin'
export { CLOWNFISH_ASSEMBLY } from './animal-clownfish'
export { RAY_ASSEMBLY } from './animal-ray'
export { EEL_ASSEMBLY } from './animal-eel'
export { ANGLERFISH_ASSEMBLY } from './animal-anglerfish'
export { SEA_URCHIN_ASSEMBLY } from './animal-sea-urchin'
export { SQUID_ASSEMBLY } from './animal-squid'
export { JELLYFISH_ASSEMBLY } from './animal-jellyfish'
export { STARFISH_ASSEMBLY } from './animal-starfish'
export { SEAHORSE_ASSEMBLY } from './animal-seahorse'
export { LOBSTER_ASSEMBLY } from './animal-lobster'
export { SWAN_ASSEMBLY } from './animal-swan'
export { HERON_ASSEMBLY } from './animal-heron'
export { STORK_ASSEMBLY } from './animal-stork'
export { FLAMINGO_ASSEMBLY } from './animal-flamingo'
export { PELICAN_ASSEMBLY } from './animal-pelican'
export { TOUCAN_ASSEMBLY } from './animal-toucan'
export { PEACOCK_ASSEMBLY } from './animal-peacock'
export { ZEBRA_ASSEMBLY } from './animal-zebra'
export { HIPPO_ASSEMBLY } from './animal-hippo'
export { CHEETAH_ASSEMBLY } from './animal-cheetah'
export { MEERKAT_ASSEMBLY } from './animal-meerkat'
export { WARTHOG_ASSEMBLY } from './animal-warthog'
export { GORILLA_ASSEMBLY } from './animal-gorilla'
export { OSTRICH_ASSEMBLY } from './animal-ostrich'
export { ANTELOPE_ASSEMBLY } from './animal-antelope'
export { MONGOOSE_ASSEMBLY } from './animal-mongoose'
export { HYENA_ASSEMBLY } from './animal-hyena'
export { BABOON_ASSEMBLY } from './animal-baboon'
export { WILDEBEEST_ASSEMBLY } from './animal-wildebeest'
export { BUFFALO_ASSEMBLY } from './animal-buffalo'
export { AARDVARK_ASSEMBLY } from './animal-aardvark'
export { VULTURE_ASSEMBLY } from './animal-vulture'
export { BUTTERFLY_ASSEMBLY } from './animal-butterfly'
export { LADYBIRD_ASSEMBLY } from './animal-ladybird'
export { DRAGONFLY_ASSEMBLY } from './animal-dragonfly'
export { ANT_ASSEMBLY } from './animal-ant'
export { BEETLE_ASSEMBLY } from './animal-beetle'
export { SPIDER_ASSEMBLY } from './animal-spider'
export { KANGAROO_ASSEMBLY } from './animal-kangaroo'
export { WOMBAT_ASSEMBLY } from './animal-wombat'
export { PLATYPUS_ASSEMBLY } from './animal-platypus'
export { EMU_ASSEMBLY } from './animal-emu'
export { ECHIDNA_ASSEMBLY } from './animal-echidna'
export { QUOKKA_ASSEMBLY } from './animal-quokka'
export { COCKATOO_ASSEMBLY } from './animal-cockatoo'
export { DINGO_ASSEMBLY } from './animal-dingo'
export { FRILLED_LIZARD_ASSEMBLY } from './animal-frilled-lizard'
export { KOOKABURRA_ASSEMBLY } from './animal-kookaburra'
export { TASSIE_DEVIL_ASSEMBLY } from './animal-tassie-devil'
export { BILBY_ASSEMBLY } from './animal-bilby'
export { NUMBAT_ASSEMBLY } from './animal-numbat'
export { BANDICOOT_ASSEMBLY } from './animal-bandicoot'
export { THORNY_DEVIL_ASSEMBLY } from './animal-thorny-devil'
export { LYREBIRD_ASSEMBLY } from './animal-lyrebird'
export { SEAL_ASSEMBLY } from './animal-seal'
export { WALRUS_ASSEMBLY } from './animal-walrus'
export { ARCTIC_FOX_ASSEMBLY } from './animal-arctic-fox'
export { REINDEER_ASSEMBLY } from './animal-reindeer'
export { SNOWY_OWL_ASSEMBLY } from './animal-snowy-owl'
export { HUSKY_ASSEMBLY } from './animal-husky'
export { ORCA_ASSEMBLY } from './animal-orca'
export { ARCTIC_HARE_ASSEMBLY } from './animal-arctic-hare'
export { MUSK_OX_ASSEMBLY } from './animal-musk-ox'
export { LEMMING_ASSEMBLY } from './animal-lemming'
export { BELUGA_ASSEMBLY } from './animal-beluga'
export { NARWHAL_ASSEMBLY } from './animal-narwhal'
export { PTARMIGAN_ASSEMBLY } from './animal-ptarmigan'
export { ERMINE_ASSEMBLY } from './animal-ermine'
export { DALL_SHEEP_ASSEMBLY } from './animal-dall-sheep'
export { SNOW_PETREL_ASSEMBLY } from './animal-snow-petrel'
export { WORM_ASSEMBLY } from './animal-worm'
export { GRASSHOPPER_ASSEMBLY } from './animal-grasshopper'
export { MOTH_ASSEMBLY } from './animal-moth'
export { WOODLOUSE_ASSEMBLY } from './animal-woodlouse'
export { SLOTH_ASSEMBLY } from './animal-sloth'
export { JAGUAR_ASSEMBLY } from './animal-jaguar'
export { TREE_FROG_ASSEMBLY } from './animal-tree-frog'
export { CHAMELEON_ASSEMBLY } from './animal-chameleon'
export { GIBBON_ASSEMBLY } from './animal-gibbon'
export { TAPIR_ASSEMBLY } from './animal-tapir'
export { SNAKE_ASSEMBLY } from './animal-snake'
export { TARANTULA_ASSEMBLY } from './animal-tarantula'
export { HUMMINGBIRD_ASSEMBLY } from './animal-hummingbird'
export { LEMUR_ASSEMBLY } from './animal-lemur'
export { ANTEATER_ASSEMBLY } from './animal-anteater'
export { CAPYBARA_ASSEMBLY } from './animal-capybara'
export { OCELOT_ASSEMBLY } from './animal-ocelot'
export { HOWLER_MONKEY_ASSEMBLY } from './animal-howler-monkey'
export { IGUANA_ASSEMBLY } from './animal-iguana'
export { COATI_ASSEMBLY } from './animal-coati'
export { SNAIL_ASSEMBLY } from './animal-snail'
export { CENTIPEDE_ASSEMBLY } from './animal-centipede'
export { MANTIS_ASSEMBLY } from './animal-mantis'
export { STICK_INSECT_ASSEMBLY } from './animal-stick-insect'
export { WASP_ASSEMBLY } from './animal-wasp'
export { SLUG_ASSEMBLY } from './animal-slug'
export { WHITE_RHINO_ASSEMBLY } from './animal-white-rhino'
export { EUROPEAN_BISON_ASSEMBLY } from './animal-european-bison'
export { MANED_WOLF_ASSEMBLY } from './animal-maned-wolf'
export { YAK_ASSEMBLY } from './animal-yak'
export { JERBOA_ASSEMBLY } from './animal-jerboa'
export { AGOUTI_ASSEMBLY } from './animal-agouti'
export { HARBOUR_PORPOISE_ASSEMBLY } from './animal-harbour-porpoise'
export { GUANACO_ASSEMBLY } from './animal-guanaco'
export { MARKHOR_ASSEMBLY } from './animal-markhor'
export { JAGUARUNDI_ASSEMBLY } from './animal-jaguarundi'
export { EMPEROR_PENGUIN_ASSEMBLY } from './animal-emperor-penguin'
export { STRIPED_HYENA_ASSEMBLY } from './animal-striped-hyena'
export { GOLDEN_EAGLE_ASSEMBLY } from './animal-golden-eagle'
export { BALD_EAGLE_ASSEMBLY } from './animal-bald-eagle'
export { HARPY_EAGLE_ASSEMBLY } from './animal-harpy-eagle'
export { RED_KITE_ASSEMBLY } from './animal-red-kite'
export { BUZZARD_ASSEMBLY } from './animal-buzzard'
export { SPARROWHAWK_ASSEMBLY } from './animal-sparrowhawk'
export { GOSHAWK_ASSEMBLY } from './animal-goshawk'
export { PEREGRINE_FALCON_ASSEMBLY } from './animal-peregrine-falcon'
export { KESTREL_ASSEMBLY } from './animal-kestrel'
export { MERLIN_ASSEMBLY } from './animal-merlin'
export { HOBBY_ASSEMBLY } from './animal-hobby'
export { OSPREY_ASSEMBLY } from './animal-osprey'
export { BARN_OWL_ASSEMBLY } from './animal-barn-owl'
export { TAWNY_OWL_ASSEMBLY } from './animal-tawny-owl'
export { EAGLE_OWL_ASSEMBLY } from './animal-eagle-owl'
export { HARRIER_ASSEMBLY } from './animal-harrier'
export { RED_PANDA_ASSEMBLY } from './animal-red-panda'
export { CHIMPANZEE_ASSEMBLY } from './animal-chimpanzee'
export { BONOBO_ASSEMBLY } from './animal-bonobo'
export { BLUE_WHALE_ASSEMBLY } from './animal-blue-whale'
export { AFRICAN_WILD_DOG_ASSEMBLY } from './animal-african-wild-dog'
export { OKAPI_ASSEMBLY } from './animal-okapi'
export { GIANT_OTTER_ASSEMBLY } from './animal-giant-otter'
export { KOMODO_DRAGON_ASSEMBLY } from './animal-komodo-dragon'
export { WHOOPING_CRANE_ASSEMBLY } from './animal-whooping-crane'
export { RED_WOLF_ASSEMBLY } from './animal-red-wolf'
export { GALAPAGOS_PENGUIN_ASSEMBLY } from './animal-galapagos-penguin'
export { TREE_KANGAROO_ASSEMBLY } from './animal-tree-kangaroo'
export { SNOW_LEOPARD_ASSEMBLY } from './animal-snow-leopard'
export { DUGONG_ASSEMBLY } from './animal-dugong'
export { SUN_BEAR_ASSEMBLY } from './animal-sun-bear'
export { MOON_BEAR_ASSEMBLY } from './animal-moon-bear'
export { SLOTH_BEAR_ASSEMBLY } from './animal-sloth-bear'
export { HYACINTH_MACAW_ASSEMBLY } from './animal-hyacinth-macaw'
export { MANDRILL_ASSEMBLY } from './animal-mandrill'
export { CASSOWARY_ASSEMBLY } from './animal-cassowary'
export { FOSSA_ASSEMBLY } from './animal-fossa'
export { TAKIN_ASSEMBLY } from './animal-takin'
export { GAUR_ASSEMBLY } from './animal-gaur'
export { MANATEE_ASSEMBLY } from './animal-manatee'
export { BLACK_RHINO_ASSEMBLY } from './animal-black-rhino'
export { VAQUITA_ASSEMBLY } from './animal-vaquita'
export { AMUR_LEOPARD_ASSEMBLY } from './animal-amur-leopard'
export { SUMATRAN_ORANGUTAN_ASSEMBLY } from './animal-sumatran-orangutan'
export { KAKAPO_ASSEMBLY } from './animal-kakapo'
export { AXOLOTL_ASSEMBLY } from './animal-axolotl'
export { PHILIPPINE_EAGLE_ASSEMBLY } from './animal-philippine-eagle'
export { SAOLA_ASSEMBLY } from './animal-saola'
export { PANGOLIN_ASSEMBLY } from './animal-pangolin'
export { GHARIAL_ASSEMBLY } from './animal-gharial'
export { SUMATRAN_RHINO_ASSEMBLY } from './animal-sumatran-rhino'
export { SPIXS_MACAW_ASSEMBLY } from './animal-spixs-macaw'
export { MAMMOTH_ASSEMBLY } from './animal-mammoth'
export { UNICORN_ASSEMBLY } from './animal-unicorn'
export { SABRE_TOOTH_ASSEMBLY } from './animal-sabre-tooth'
export { DODO_ASSEMBLY } from './animal-dodo'
export { MEGALODON_ASSEMBLY } from './animal-megalodon'
export { DIRE_WOLF_ASSEMBLY } from './animal-dire-wolf'
export { GIANT_SLOTH_ASSEMBLY } from './animal-giant-sloth'
export { TERROR_BIRD_ASSEMBLY } from './animal-terror-bird'
export { WOOLLY_RHINO_ASSEMBLY } from './animal-woolly-rhino'
export { QUAGGA_ASSEMBLY } from './animal-quagga'
export { GLYPTODON_ASSEMBLY } from './animal-glyptodon'
export { CAVE_BEAR_ASSEMBLY } from './animal-cave-bear'
export { IRISH_ELK_ASSEMBLY } from './animal-irish-elk'
export { DRAGON_ASSEMBLY } from './animal-dragon'
export { PHOENIX_ASSEMBLY } from './animal-phoenix'
export { GRIFFIN_ASSEMBLY } from './animal-griffin'
export { HIPPOGRIFF_ASSEMBLY } from './animal-hippogriff'
export { T_REX_ASSEMBLY } from './animal-t-rex'
export { TRICERATOPS_ASSEMBLY } from './animal-triceratops'
export { STEGOSAURUS_ASSEMBLY } from './animal-stegosaurus'
export { BRACHIOSAURUS_ASSEMBLY } from './animal-brachiosaurus'
export { PTERODACTYL_ASSEMBLY } from './animal-pterodactyl'
export { VELOCIRAPTOR_ASSEMBLY } from './animal-velociraptor'
export { ANKYLOSAURUS_ASSEMBLY } from './animal-ankylosaurus'
export { DIPLODOCUS_ASSEMBLY } from './animal-diplodocus'
export { SPINOSAURUS_ASSEMBLY } from './animal-spinosaurus'
export { ALLOSAURUS_ASSEMBLY } from './animal-allosaurus'
export { PARASAUROLOPHUS_ASSEMBLY } from './animal-parasaurolophus'
export { IGUANODON_ASSEMBLY } from './animal-iguanodon'
export { PACHYCEPHALOSAURUS_ASSEMBLY } from './animal-pachycephalosaurus'
export { DILOPHOSAURUS_ASSEMBLY } from './animal-dilophosaurus'
export { GALLIMIMUS_ASSEMBLY } from './animal-gallimimus'
export { CARNOTAURUS_ASSEMBLY } from './animal-carnotaurus'
export { YETI_ASSEMBLY } from './animal-yeti'
export { KRAKEN_ASSEMBLY } from './animal-kraken'
export { LOCH_NESS_ASSEMBLY } from './animal-loch-ness'
export { JACKALOPE_ASSEMBLY } from './animal-jackalope'
export { THUNDERBIRD_ASSEMBLY } from './animal-thunderbird'
export { SPHINX_ASSEMBLY } from './animal-sphinx'
export { MOON_RABBIT_ASSEMBLY } from './animal-moon-rabbit'
/* -- append the next species' line directly above this one -- */

import { assembledBuilds } from './register'

/**
 * Every species the assembly kit can build, by species id.
 *
 * Derived from the register rather than typed out, which is the half of the
 * split that stops "added the file, forgot the map" being a thing that can
 * happen. Frozen at module load: every re-export above has already been
 * evaluated by the time this line runs, because `export ... from` is hoisted.
 */
export const ASSEMBLED_BUILDS = assembledBuilds()

export { assemblyFor, assembledCount } from './register'
