/**
 * The ONE animal approver — one row per assembled creature, joined to its fact
 * and to everything Joe has already said about it, with a single action at the
 * end of it.
 *
 * JOE_WORKBENCH_ONLY.
 *
 * This replaces `built.ts`, which benched the seventy-two the kits built. Joe,
 * 29 July 2026: *"everything built already in terms of animals is scrap. names
 * and facts ok, the 3D part is junk i'm afraid."* So the models are new — they
 * come out of `src/island/species/parts`, assembled from geometry lifted out of
 * the authored Kenney packs — and the names and the facts survive untouched,
 * which is why this file still reads `joe/names-audit.json` and
 * `joe/species-facts.json` exactly as its predecessor did.
 *
 * What it keeps from `built.ts` is the ruling underneath it (JT-031): *"have an
 * agent create the facts and fact check them. they then become part of my final
 * sign off for each animal along with its name."* One creature, one judgement,
 * covering the model, the collection, the name and the fact together.
 *
 * ## Why this file has no three.js in it
 *
 * Everything here is the JOIN — which creatures are benched, what each is
 * called, what is known about it, what he has said, how far through he is. None
 * of that needs a renderer, and keeping it out means the arithmetic behind "3 of
 * 12 approved" is testable in node against the real assembled set rather than
 * only observable by looking at a page. `viewer.ts` owns the geometry; this owns
 * the facts.
 *
 * ## The bench is exhaustive, and that is a promise rather than a side effect
 *
 * `approverBench` emits one `Creature` per row it is given, in the order it is
 * given them, whether or not the audit file has heard of the creature and
 * whether or not a fact has been drafted for it. There is deliberately no branch
 * that can skip a species: a gallery that inherited an unwritten `else` once
 * listed props to Joe, and a bench that quietly drops the animals its side files
 * have not caught up with would make the progress count a lie in the same silent
 * way. A creature nothing is known about is shown, marked, and counted.
 */
import { COLLECTIONS } from '../../../src/island/species/roster'
import type { AssembledRow } from './assembled'

/**
 * One row of `joe/names-audit.json`, as it arrives from `/api/state`.
 *
 * Every field is optional because the file is generated by whatever run last
 * built the roster, and three of them — `signoff`, `factVerdict`, `factNote` —
 * are newer than most rows on disk. An absent field and an empty one mean the
 * same thing here and in `merge.mjs`: nothing has been said yet.
 */
export interface AuditRow {
  id: string
  setId?: string
  speciesId?: string
  species?: string
  collection?: string
  band?: string
  name?: string
  /** The NAME's verdict — 'ok' or 'reject'. Not the gate; see `signoff`. */
  verdict?: string
  replacement?: string
  note?: string
  /** THE gate. 'ok' means the whole creature may ship. */
  signoff?: string
  /** The FACT's verdict — 'ok' or 'reject'. Not the gate either. */
  factVerdict?: string
  factNote?: string
}

/** The one value an approval or a verdict takes to mean yes. */
export const APPROVED = 'ok'
/** And the one it takes to mean no — struck, deliberately, by him. */
export const STRUCK = 'reject'

/**
 * One species' fact, as the drafting agent leaves it in
 * `joe/species-facts.json`.
 *
 * >>> THAT FILE IS NOT WRITTEN BY THIS CODE AND ITS SHAPE IS NOT OURS.
 *
 * A separate agent drafts each sentence and fact-checks it, per JT-031, and it
 * owns the file outright — nothing in the workbench writes there, so the two
 * sides can never collide over it. The reader below therefore stays tolerant
 * about the keys it accepts even now that the file exists, because the agent
 * that regenerates it is not obliged to ask us first, and guessing wrong would
 * render a page of blanks that looks like an empty file rather than a mismatch.
 * <<<
 */
export interface FactRow {
  /** `Species.id`, with any `natural/` prefix already stripped. */
  speciesId: string
  /** The sentence a child is shown. '' means it has not been drafted. */
  fact: string
  /**
   * What the checking pass concluded: `verified`, `unverified`, `flagged`, or
   * '' when the file said nothing. NEVER inferred from the sentence existing —
   * an unchecked fact and a checked one look identical, which is the whole
   * reason the field is separate.
   */
  check: string
  /** Where it came from, as the checker recorded it. */
  source: string
  /**
   * What the source actually SAYS, in the checker's words.
   *
   * Shown beside the fact because a bare URL is not evidence to a man reading
   * twelve of these in a sitting: the note is what lets him agree or disagree
   * with the check without opening a browser.
   */
  sourceNote: string
  /**
   * A wording the checker would rather have, when it had one.
   *
   * The drafting side's proposal, never applied by anything here. It is offered
   * to Joe as a suggestion he can take or ignore; only his verdict is written.
   */
  proposedRewrite: string
}

/** `verified` is the only value that means a human-checkable source backed it. */
export const VERIFIED = 'verified'

/** What the button says, and it names all three things one click covers. */
export const APPROVE_LABEL = 'Approve — name, fact and model'
/** What it says afterwards. A tick he can take back is worth more than a lock. */
export const REOPEN_LABEL = '✓ approved — click to re-open'
/**
 * Why a creature cannot be approved at all, prefixed by the species id.
 *
 * The same sentence the built bench used, kept word for word so that the state
 * he has seen before reads the same way now: the animal is real and the file has
 * simply not caught up with it.
 */
export const NO_AUDIT_ROW = 'has no row in joe/names-audit.json, so it cannot be approved yet'

const str = (v: unknown): string => (typeof v === 'string' ? v.trim() : '')

const first = (record: Record<string, unknown>, keys: readonly string[]): string => {
  for (const k of keys) {
    const v = record[k]
    if (typeof v === 'string' && v.trim() !== '') return v.trim()
    if (Array.isArray(v) && v.length) return v.filter(x => typeof x === 'string').join(' · ')
  }
  return ''
}

/**
 * Read whatever `joe/species-facts.json` turns out to be.
 *
 * Tolerant on purpose, and only in the two ways that cost nothing: the records
 * may be an array or a map, and each may name its sentence, its check and its
 * source under any of a few obvious keys. Everything else is refused by being
 * ignored — an unrecognised record produces no fact, which the page shows as
 * "no fact yet", which is true.
 *
 * A boolean `verified` is translated rather than trusted as a string, because
 * `false` must not become the empty "nothing was said" state: a fact that FAILED
 * its check is a different thing from one that has not had one.
 *
 * Returns a list rather than a map because a list is what the file holds and
 * what the caller passes on; the one place a lookup is wanted — the join in
 * `approverBench` — builds its own index and is the only thing that needs one.
 */
export function readFacts(raw: unknown): FactRow[] {
  if (raw === null || typeof raw !== 'object') return []

  const holder = raw as Record<string, unknown>
  const entries = Array.isArray(raw) ? raw
    : Array.isArray(holder['facts']) ? holder['facts'] as unknown[]
      : Array.isArray(holder['species']) ? holder['species'] as unknown[]
        : typeof holder['facts'] === 'object' && holder['facts'] !== null
          ? Object.entries(holder['facts'] as Record<string, unknown>)
            .map(([k, v]) => (v !== null && typeof v === 'object' ? { speciesId: k, ...v } : v))
          : []

  const out: FactRow[] = []
  for (const entry of entries) {
    if (entry === null || typeof entry !== 'object') continue
    const record = entry as Record<string, unknown>
    /* `natural/animal-fox` and `animal-fox` are the same creature. The audit
     * file keys one way and the roster the other; either is accepted. */
    const key = first(record, ['speciesId', 'species', 'id'])
    const speciesId = key.includes('/') ? key.slice(key.lastIndexOf('/') + 1) : key
    if (!speciesId) continue

    const verified = record['verified']
    const check = typeof verified === 'boolean' ? (verified ? VERIFIED : 'flagged')
      : first(record, ['check', 'status', 'checked', 'verified'])

    out.push({
      speciesId,
      fact: first(record, ['fact', 'text', 'info', 'sentence', 'summary']),
      check,
      source: first(record, ['source', 'sources', 'reference', 'citation', 'url']),
      sourceNote: first(record, ['sourceNote', 'sourceNotes', 'evidence', 'quote']),
      proposedRewrite: first(record, ['proposedRewrite', 'rewrite', 'suggestion']),
    })
  }
  return out
}

/** One assembled animal, everything he needs to judge it in one place. */
export interface Creature {
  /** `AssembledRow.id`, which is `Species.id`. SAVED into a child's island. */
  speciesId: string
  /**
   * The audit row's key, `natural/<speciesId>`, and the id a patch must name.
   *
   * Separate from `speciesId` for the same reason `Entry.file` is separate from
   * `Entry.id` in `registry.ts`: they are not the same string, and holding only
   * one of them is how a viewer ends up confidently reporting nothing.
   */
  auditId: string
  /** The real species name, printed in the album. "Hedgehog". */
  species: string
  /** `Collection.id` — `garden`, `africa`. */
  collection: string
  /** `Collection.name` — the album page's title, or the raw id when unknown. */
  collectionName: string
  /** The build's own note about a rule it strained, or ''. */
  flag: string
  flagged: boolean
  /** The build named a collection the roster does not have. Shown, not hidden. */
  unknownCollection: boolean
  /** The alien word the audit file gave this creature. "Nachet". */
  given: string
  /** The species name the audit row was written against. */
  benched: string
  /**
   * The audit row and the roster disagree about what this creature IS.
   *
   * Not an error and not hidden: the audit file is generated, so it goes stale
   * against a roster that moves under it, and this is what that looks like from
   * the outside. Joe must not approve a row the roster no longer agrees with.
   */
  drift: boolean
  /** Which name band the collection draws its given names from. */
  band: string
  /** True when `joe/names-audit.json` has a row for this creature. */
  onBench: boolean
  /** The drafted sentence, or '' if the fact agent has not reached it. */
  fact: string
  /** What the checking pass concluded. '' means no check was recorded. */
  factCheck: string
  factSource: string
  /** What the source says, in the checker's words. */
  sourceNote: string
  /** The checker's suggested wording, offered and never applied. */
  proposedRewrite: string
  /** THE gate: 'ok' when Joe has approved the whole creature. */
  signoff: string
  /** His judgement on the NAME alone. */
  verdict: string
  replacement: string
  note: string
  /** His judgement on the FACT alone. */
  factVerdict: string
  factNote: string
}

/**
 * Every assembled species, benched against its fact and against what he has said.
 *
 * The three inputs are passed in rather than read here so the join is provable
 * against fixtures: the rows come from `assembledRows(assembledSpecies())`, the
 * audit rows and the facts off `/api/state`. Any of the three may be empty, and
 * an empty one costs the bench nothing but detail — see the exhaustiveness note
 * at the top of the file, which is the reason this function has no `filter` and
 * no `else`.
 */
export function approverBench(
  rows: readonly AssembledRow[],
  audit: readonly AuditRow[],
  facts: readonly FactRow[],
): Creature[] {
  const byAuditId = new Map(audit.map(r => [r.id, r]))
  const byFactId = new Map(facts.map(f => [f.speciesId, f]))
  const bands = new Map(COLLECTIONS.map(c => [c.id, c.band as string]))

  return rows.map((row): Creature => {
    const auditId = `natural/${row.id}`
    const audited = byAuditId.get(auditId)
    const fact = byFactId.get(row.id)
    const benched = str(audited?.species)
    return {
      speciesId: row.id,
      auditId,
      species: row.name,
      collection: row.collection,
      collectionName: row.collectionName,
      flag: row.flag,
      flagged: row.flagged,
      unknownCollection: row.unknownCollection,
      given: str(audited?.name),
      benched,
      /* Only a row that actually names a species can disagree about one. */
      drift: benched !== '' && benched !== row.name,
      /* The roster's band, and the row's only as a fallback: the generated file
       * goes stale and the code's table does not. */
      band: bands.get(row.collection) ?? str(audited?.band),
      onBench: audited !== undefined,
      fact: fact?.fact ?? '',
      factCheck: fact?.check ?? '',
      factSource: fact?.source ?? '',
      sourceNote: fact?.sourceNote ?? '',
      proposedRewrite: fact?.proposedRewrite ?? '',
      signoff: str(audited?.signoff),
      verdict: str(audited?.verdict),
      replacement: str(audited?.replacement),
      note: str(audited?.note),
      factVerdict: str(audited?.factVerdict),
      factNote: str(audited?.factNote),
    }
  })
}

/*
 * ONE ACTION, THREE VERDICTS — the design decision of this whole run.
 *
 * Joe asked for a single approval per animal: he looks at the model, reads the
 * name and the fact beside it, and says yes once. One button, one click, one
 * thing to remember. But the three judgements must still land in THREE FIELDS,
 * and the reason is written into `merge.mjs` already: `verdict` is the name-only
 * judgement made by reading a word aloud in the old names list, and folding it
 * into the gate would let a name ticked in a list count as an animal he had
 * actually looked at. So `signoff` remains the gate over the whole creature, and
 * `verdict` and `factVerdict` remain the per-part judgements, and one click
 * writes all three.
 *
 * The other half of it is the strikes. Striking the name or the fact is a
 * considered act — he read the word or the sentence and said no to it — and it
 * is not a refusal of the ANIMAL. He must be able to accept the creature while
 * holding that the name is wrong, which is precisely the case JT-031 needs a way
 * to express. So an existing 'reject' SURVIVES the approve rather than being
 * overwritten by it, and re-opening clears only what the approve set. Nothing in
 * this pair of functions can ever erase a judgement he made by hand; the worst
 * either can do is take back a tick, which is exactly what re-open is for.
 *
 * Both return plain patches — the fields and nothing else — so `/api/save` folds
 * them into whatever the generator has since rewritten around them. Every key
 * either produces is owned by the `names` record in `merge.mjs`, and the test
 * asserts that by reading the file rather than by trusting this comment.
 */

/** One click: the creature is approved, and any strike he already made stands. */
export function approvePatch(c: Creature): Record<string, string> {
  return {
    signoff: APPROVED,
    verdict: c.verdict === STRUCK ? STRUCK : APPROVED,
    factVerdict: c.factVerdict === STRUCK ? STRUCK : APPROVED,
  }
}

/** The same click again: the approvals come off, the strikes do not. */
export function reopenPatch(c: Creature): Record<string, string> {
  return {
    signoff: '',
    verdict: c.verdict === STRUCK ? STRUCK : '',
    factVerdict: c.factVerdict === STRUCK ? STRUCK : '',
  }
}

/** How far he has got. The numbers always describe the WHOLE bench. */
export interface Progress {
  total: number
  /** Approved outright — the gate, and nothing else, is 'ok'. */
  approved: number
  left: number
  /** No sentence drafted yet — the fact agent has not reached these. */
  withoutFact: number
  /** A sentence exists but nothing checked it, or the check flagged it. */
  unverified: number
  /** Names he has struck. Counted separately because they are not rejections. */
  struckName: number
  /** Facts he has struck, likewise. */
  struckFact: number
  /** Benched but with no row in `joe/names-audit.json`, so unapprovable. */
  unsignable: number
  /** What the bar says. "3 of 12 approved". */
  label: string
  /**
   * The clauses under the bar, in one fixed order, and only the non-zero ones.
   *
   * Fixed so that a number he has learned the position of does not move when
   * another one goes to zero, and silent when zero because a row of "0 struck"
   * teaches him to stop reading the line at all.
   */
  meta: string[]
}

const clause = (n: number, one: string, many: string): string =>
  `${n} ${n === 1 ? one : many}`

export function progressOf(bench: readonly Creature[]): Progress {
  const total = bench.length
  const approved = bench.filter(c => c.signoff === APPROVED).length
  const left = total - approved
  const withoutFact = bench.filter(c => c.fact === '').length
  const unverified = bench.filter(c => c.fact !== '' && c.factCheck !== VERIFIED).length
  const struckName = bench.filter(c => c.verdict === STRUCK).length
  const struckFact = bench.filter(c => c.factVerdict === STRUCK).length
  const unsignable = bench.filter(c => !c.onBench).length

  const meta: string[] = []
  if (left) meta.push(`${left} to go`)
  if (unverified) meta.push(clause(unverified, 'fact unverified', 'facts unverified'))
  if (withoutFact) meta.push(`${withoutFact} with no fact yet`)
  if (struckName) meta.push(clause(struckName, 'name struck', 'names struck'))
  if (struckFact) meta.push(clause(struckFact, 'fact struck', 'facts struck'))
  if (unsignable) meta.push(`${unsignable} not in the audit file`)

  return {
    total,
    approved,
    left,
    withoutFact,
    unverified,
    struckName,
    struckFact,
    unsignable,
    label: `${approved} of ${total} approved`,
    meta,
  }
}
