/**
 * The bench of BUILT animals — one row per creature the kits construct, joined
 * to its fact and to the judgement Joe has recorded about it.
 *
 * JOE_WORKBENCH_ONLY.
 *
 * Joe, 29 July: *"can i look at built animals in the workbench and where do i
 * see their names? i suggest the asset viewer shows assigned collection and name
 * as well as the short info text about each. i then sign them off one by one and
 * you show me the progress in the viewer."*
 *
 * And, on where the fact text comes from (JT-031): *"have an agent create the
 * facts and fact check them. they then become part of my final sign off for each
 * animal along with its name."* That ruling is the shape of this file. There is
 * ONE gate per creature — `signoff` — and it covers the model, the collection,
 * the name and the fact together, because his sign-off was always the real
 * check. What the surface must let him do is strike ONE part of it while keeping
 * the rest, which is why the name and the fact each carry their own verdict and
 * note without either becoming a second gate.
 *
 * ## Why this file has no three.js in it
 *
 * Everything here is the JOIN — which species are built, what collection each
 * belongs to, what it is called, what is known about it, what he has said, how
 * far through he is. None of that needs a renderer, and keeping it out means the
 * arithmetic behind "34 of 50 signed off" is testable in node against the real
 * registry rather than only observable by looking at a page. `viewer.ts` owns
 * the geometry; this owns the facts.
 *
 * ## Where every field comes from, and why none of them is typed here
 *
 * `registry.ts` in this folder set the precedent and the reason: an ID that was
 * typed into a tool is wrong within a week and confidently wrong forever after.
 * So the species come from `SHIPPED_SPECIES`, the collection and its band from
 * `COLLECTIONS`, and the given name from `givenName()` — the same function the
 * hatch will call. If the manager adds a collection while Joe has the page open,
 * a reload shows it.
 *
 * Two things cannot come from the code. His judgement comes off
 * `joe/names-audit.json`, and the fact sentences come off
 * `joe/species-facts.json`, both through `/api/state`. A creature missing either
 * is still benched — visibly, and marked — because a species the audit file has
 * not caught up with is a real state, and hiding it would make the progress
 * count a lie.
 */
import { SHIPPED_SPECIES } from '../../../src/island/species/registry'
import { COLLECTIONS } from '../../../src/island/species/roster'
import { givenName, NATURAL_SET } from '../../../src/island/species/naming'
import type { Collection, Species } from '../../../src/island/species/types'

/**
 * One row of `joe/names-audit.json`, as it arrives from `/api/state`.
 *
 * Every field is optional because the file is generated by whatever run last
 * built the roster, and three of them — `signoff`, `factVerdict`, `factNote` —
 * are newer than every row now on disk. An absent field and an empty one mean
 * the same thing here and in `merge.mjs`: nothing has been said yet.
 */
export interface AuditRow {
  id: string
  setId?: string
  speciesId?: string
  species?: string
  collection?: string
  band?: string
  name?: string
  /** The NAME's verdict — 'ok' or 'reject'. Not the gate; see `signoff`. */
  verdict?: string
  replacement?: string
  note?: string
  /** THE gate. 'ok' means the whole creature may ship. */
  signoff?: string
  /** The FACT's verdict — 'ok' or 'reject'. Not the gate either. */
  factVerdict?: string
  factNote?: string
}

/** The one value a verdict or a sign-off takes to mean yes. */
export const SIGNED_OFF = 'ok'
export const STRUCK = 'reject'

/**
 * One species' fact, as the drafting agent leaves it in
 * `joe/species-facts.json`.
 *
 * >>> THAT FILE IS NOT WRITTEN BY THIS CODE AND ITS SHAPE IS NOT OURS.
 *
 * A separate agent drafts each sentence and fact-checks it, per JT-031, and it
 * owns the file outright — nothing in the workbench writes there, so the two
 * sides can never collide over it. The consequence is that this reader lands
 * before the file does and must not be brittle about the exact keys it finds,
 * because guessing wrong would render fifty blanks and look like an empty file
 * rather than a mismatch. `readFacts` therefore accepts the handful of shapes
 * the same content could reasonably arrive in and normalises them to this. When
 * the file exists, pin the real shape here and delete the tolerance.
 * <<<
 */
export interface FactRow {
  /** `Species.id`, with any `natural/` prefix already stripped. */
  speciesId: string
  /** The sentence a child is shown. '' means it has not been drafted. */
  fact: string
  /**
   * What the checking pass concluded: `verified`, `unverified`, `flagged`, or
   * '' when the file said nothing. NEVER inferred from the sentence existing —
   * an unchecked fact and a checked one look identical, which is the whole
   * reason the field is separate.
   */
  check: string
  /** Where it came from, as the checker recorded it. */
  source: string
}

/** `verified` is the only value that means a human-checkable source backed it. */
export const VERIFIED = 'verified'

const str = (v: unknown): string => (typeof v === 'string' ? v.trim() : '')

const first = (record: Record<string, unknown>, keys: readonly string[]): string => {
  for (const k of keys) {
    const v = record[k]
    if (typeof v === 'string' && v.trim() !== '') return v.trim()
    if (Array.isArray(v) && v.length) return v.filter(x => typeof x === 'string').join(' · ')
  }
  return ''
}

/**
 * Read whatever `joe/species-facts.json` turns out to be, keyed by species id.
 *
 * Tolerant on purpose, and only in the two ways that cost nothing: the records
 * may be an array or a map, and each may name its sentence, its check and its
 * source under any of a few obvious keys. Everything else is refused by being
 * ignored — an unrecognised record produces no fact, which the page shows as
 * "no fact yet", which is true.
 *
 * A boolean `verified` is translated rather than trusted as a string, because
 * `false` must not become the empty "nothing was said" state: a fact that FAILED
 * its check is a different thing from one that has not had one.
 */
export function readFacts(file: unknown): Map<string, FactRow> {
  const out = new Map<string, FactRow>()
  if (file === null || typeof file !== 'object') return out

  const holder = file as Record<string, unknown>
  const raw = Array.isArray(file) ? file
    : Array.isArray(holder['facts']) ? holder['facts'] as unknown[]
      : Array.isArray(holder['species']) ? holder['species'] as unknown[]
        : typeof holder['facts'] === 'object' && holder['facts'] !== null
          ? Object.entries(holder['facts'] as Record<string, unknown>)
            .map(([k, v]) => (v !== null && typeof v === 'object' ? { speciesId: k, ...v } : v))
          : []

  for (const entry of raw) {
    if (entry === null || typeof entry !== 'object') continue
    const record = entry as Record<string, unknown>
    /* `natural/animal-fox` and `animal-fox` are the same creature. The audit
     * file keys one way and the roster the other; either is accepted. */
    const key = first(record, ['speciesId', 'species', 'id'])
    const speciesId = key.includes('/') ? key.slice(key.lastIndexOf('/') + 1) : key
    if (!speciesId) continue

    const verified = record['verified']
    const check = typeof verified === 'boolean' ? (verified ? VERIFIED : 'flagged')
      : first(record, ['check', 'status', 'checked', 'verified'])

    out.set(speciesId, {
      speciesId,
      fact: first(record, ['fact', 'text', 'info', 'sentence', 'summary']),
      check,
      source: first(record, ['source', 'sources', 'reference', 'citation', 'url']),
    })
  }
  return out
}

/** One built animal, everything about it in one place. */
export interface Creature {
  /** `Species.id`. SAVED into every child's island — never renamed. */
  speciesId: string
  /**
   * The audit row's key, `natural/<speciesId>`, and the id a patch must name.
   *
   * Separate from `speciesId` for the same reason `Entry.file` is separate from
   * `Entry.id` in `registry.ts`: they are not the same string, and holding only
   * one of them is how a viewer ends up confidently reporting nothing.
   */
  auditId: string
  /** The real species name, printed in the album. "Hedgehog". */
  species: string
  /** The given name as the code generates it TODAY. */
  given: string
  /** The given name the audit row was written with. */
  benched: string
  /**
   * The two disagree, so the file is stale against the roster.
   *
   * Not an error and not hidden: `naming.ts` warns that inserting a species
   * mid-roster renames the ones after it, and this is what that looks like from
   * the outside. Joe must not sign off a name the file no longer agrees with.
   */
  drift: boolean
  /** `Collection.id` — `garden`, `africa`. */
  collection: string
  /** `Collection.name` — the album page's title. */
  collectionName: string
  /** Where the collection sits in the ship queue. */
  ship: number
  band: string
  kit: string
  /** True when `joe/names-audit.json` has a row for this creature. */
  onBench: boolean
  /** The drafted sentence, or '' if the fact agent has not reached it. */
  fact: string
  /** What the checking pass concluded. '' means no check was recorded. */
  factCheck: string
  factSource: string
  /** THE gate: 'ok' when Joe has signed the whole creature off. */
  signoff: string
  /** His judgement on the NAME alone. */
  verdict: string
  replacement: string
  note: string
  /** His judgement on the FACT alone. */
  factVerdict: string
  factNote: string
}

/**
 * Where the facts come from. Defaulted to the live tables; injectable so the
 * join can be tested against a roster that does not move under the test.
 */
export interface Sources {
  species: readonly Species[]
  collections: readonly Collection[]
  given(speciesId: string): string
  naturalSet: string
}

export const LIVE: Sources = {
  species: SHIPPED_SPECIES,
  collections: COLLECTIONS,
  given: givenName,
  naturalSet: NATURAL_SET,
}

/**
 * The order Joe reads them in: ship order, then the roster's own order inside a
 * collection.
 *
 * The same order `joe/names-audit.json` is generated in, deliberately — a
 * creature that sits eleventh in the file sits eleventh on this page, so his
 * place in one is his place in the other. Never sorted by name or by whether it
 * is signed off: a row that moves under the cursor takes his place with it.
 */
function rank(collections: readonly Collection[]): Map<string, number> {
  const out = new Map<string, number>()
  const ordered = [...collections].sort((a, b) => a.ship - b.ship
    || collections.indexOf(a) - collections.indexOf(b))
  let n = 0
  for (const c of ordered) for (const id of c.members) out.set(id, n++)
  return out
}

/**
 * Every species a kit BUILDS, benched against its fact and against what Joe has
 * said about it.
 *
 * `build` present is the definition of "built", and it is exactly the line the
 * live 24 fall the other side of: they carry `kit: 'kenney'` and no `build`
 * because they are authored GLBs that `pets.ts:560` loads, frozen by roster §1.
 * They already have their own gallery in this viewer, loaded through the game's
 * own GLTF loader. This page is the other kind, and mixing them would put
 * twenty-four animals in front of Joe that he cannot change and did not ask to
 * see.
 */
export function builtBench(
  rows: readonly AuditRow[],
  facts: ReadonlyMap<string, FactRow> = new Map(),
  from: Sources = LIVE,
): Creature[] {
  const byId = new Map(rows.map(r => [r.id, r]))
  const order = rank(from.collections)
  const collections = new Map(from.collections.map(c => [c.id, c]))

  return from.species
    .filter(s => s.build !== undefined)
    .map((s): Creature => {
      const auditId = `${from.naturalSet}/${s.id}`
      const row = byId.get(auditId)
      const collection = collections.get(s.collection)
      const fact = facts.get(s.id)
      const given = from.given(s.id)
      const benched = str(row?.name)
      return {
        speciesId: s.id,
        auditId,
        species: s.name,
        given,
        benched,
        /* Only a row that actually carries a name can disagree with one. */
        drift: benched !== '' && benched !== given,
        collection: s.collection,
        collectionName: collection?.name ?? s.collection,
        ship: collection?.ship ?? Number.MAX_SAFE_INTEGER,
        band: collection?.band ?? str(row?.band),
        kit: s.kit,
        onBench: row !== undefined,
        fact: fact?.fact ?? '',
        factCheck: fact?.check ?? '',
        factSource: fact?.source ?? '',
        signoff: str(row?.signoff),
        verdict: str(row?.verdict),
        replacement: str(row?.replacement),
        note: str(row?.note),
        factVerdict: str(row?.factVerdict),
        factNote: str(row?.factNote),
      }
    })
    .sort((a, b) => (order.get(a.speciesId) ?? Number.MAX_SAFE_INTEGER)
      - (order.get(b.speciesId) ?? Number.MAX_SAFE_INTEGER))
}

/** How far he has got. The numbers always describe the WHOLE bench. */
export interface Progress {
  done: number
  total: number
  left: number
  /** No sentence drafted yet — the fact agent has not reached these. */
  withoutFact: number
  /** A sentence exists but nothing checked it, or the check flagged it. */
  unverified: number
  /**
   * Signed off while no fact existed to sign off.
   *
   * His ruling makes the fact part of the sign-off, so this counts the ticks
   * that could not possibly have covered one. It does not PREVENT them: landing
   * before the fact agent and locking the whole surface would leave him unable
   * to judge fifty models he asked to see. Counted, shown, and re-openable one
   * click at a time.
   */
  signedWithoutFact: number
  /** Benched but with no row in `joe/names-audit.json`, so unsignable. */
  unsignable: number
  /** What the bar says. "34 of 50 signed off". */
  label: string
}

export function progressOf(bench: readonly Creature[]): Progress {
  const total = bench.length
  const signed = bench.filter(c => c.signoff === SIGNED_OFF)
  return {
    done: signed.length,
    total,
    left: total - signed.length,
    withoutFact: bench.filter(c => c.fact === '').length,
    unverified: bench.filter(c => c.fact !== '' && c.factCheck !== VERIFIED).length,
    signedWithoutFact: signed.filter(c => c.fact === '').length,
    unsignable: bench.filter(c => !c.onBench).length,
    label: `${signed.length} of ${total} signed off`,
  }
}
