/**
 * The bench of PRIMITIVES — one row per shape decision the kits are waiting on,
 * joined to the verdict Joe has recorded against it.
 *
 * JOE_WORKBENCH_ONLY.
 *
 * RETIRED 29 July 2026 on Joe's instruction — *"we can drop the primitives
 * tab"* — along with the kit builds the measurements were taken to fix. The tab
 * is gone from the viewer and the file stays here as the written record of the
 * measurements themselves, which are true about the Kenney pack whatever we
 * build out of it.
 *
 * Joe looked at the 72 procedurally-built animals and said they are too square,
 * that the legs and feet are too big, and that the eyes are inconsistent. Then,
 * of the fix: *"i'd like to sign off the primitives to be used first."*
 *
 * That sentence is the whole shape of this file, and it is worth being precise
 * about what it is NOT. He is not signing off animals here — `built.ts` is the
 * bench for that. He is signing off **the shapes a kit is allowed to build out
 * of**, one at a time, and NOTHING may be re-tuned until he has ticked the
 * primitive it rides on. So a row is not a bug report and not a proposal to
 * approve in prose: it is one question, the measured answer from the Kenney
 * pack, what the kits do instead, and the discrepancy between them.
 *
 * ## Why this file has no three.js in it
 *
 * Copied from `built.ts`, deliberately and in every respect. Everything here is
 * the JOIN — which primitives are benched, in what order, carrying what
 * measurement, and what he has said — and none of it needs a renderer. Keeping
 * the renderer out is what lets "3 of 8 signed off" be asserted in node against
 * the real row set rather than only observed by looking at a page. `viewer.ts`
 * owns the geometry; this owns the decisions.
 *
 * ## The two fields that are HIS, and the contract that protects them
 *
 * `signoff` and `note` are Joe's. Every other field is MEASURED, and is
 * regenerated by whichever agent last went and measured it — which is the same
 * two-writer shape `joe/names-audit.json` has, from the same direction: the list
 * is generated, a couple of fields per row are a judgement made once by a human
 * looking at a thing. A regeneration must therefore be incapable of costing him
 * a verdict. Two mechanisms hold that, and both are tested:
 *
 *   THROUGH THE API. `merge.mjs` owns `primitives` with `signoff` as a flag and
 *   `note` as text, so `/api/save` re-reads the file inside the request and
 *   folds. An absent or empty `signoff` is the ABSENCE of a decision and can
 *   never untick an 'ok'; two meaningful notes are a 409 rather than a guess.
 *
 *   DIRECTLY ON THE FILE. An agent that rewrites `joe/primitives-audit.json`
 *   with `writeFileSync` — which is how it really happens — never touches the
 *   API, so `regenerate()` below is the same contract in a function, and a row
 *   the fresh measurement no longer produces is KEPT rather than dropped.
 *
 * ## Why `signoff` is a whole word and not a boolean
 *
 * '' is not-yet-judged, 'ok' is accept, 'reject' is refuse — three states, and
 * the first two are NOT the same thing. A bench with a boolean on it cannot tell
 * "he has not got to this one" from "he looked and said no", and the second is
 * the answer that stops a kit being re-tuned. `signedOff()` matches 'ok' and
 * nothing else, so a typo in the file shows up in the `odd` count rather than
 * silently reading as a tick.
 */
import { SPECIES } from '../../../src/island/pets'
import { SHIPPED_SPECIES } from '../../../src/island/species/registry'
/* The two verdict tokens come from the animal approver rather than being written
 * again here. They are the same words in the same file format, and two copies of
 * the string 'ok' is how one of them ends up being 'OK'. They moved out of
 * `built.ts` when the seventy-two kit builds it benched were scrapped; the token
 * `approver.ts` calls APPROVED is the same 'ok' this file has always meant. */
import { APPROVED as SIGNED_OFF, STRUCK } from './approver'

export { SIGNED_OFF, STRUCK }

/**
 * The groups, in the order he reads them.
 *
 * The array IS the type, for the reason `registry.ts GALLERIES` is written the
 * same way: a hand-typed union beside a hand-typed order array drifts, and the
 * drift is invisible. More groups land later; adding one here is what gives it a
 * heading and a place in the order, and `COMPARISON_BY_GROUP` below will not
 * compile until it also has a side-by-side.
 */
export const PRIMITIVE_GROUPS = ['Face', 'Edges', 'Limbs'] as const
export type PrimitiveGroup = typeof PRIMITIVE_GROUPS[number]

const isGroup = (v: unknown): v is PrimitiveGroup =>
  typeof v === 'string' && (PRIMITIVE_GROUPS as readonly string[]).includes(v)

/**
 * One row of `joe/primitives-audit.json`, as it arrives from `/api/state`.
 *
 * Every field but `id` is optional, for the reason `built.ts AuditRow`'s are:
 * the file is written by whichever run last measured the pack, rows arrive that
 * this build has never seen, and an absent field and an empty one mean the same
 * thing here and in `merge.mjs` — nothing has been said yet.
 */
export interface PrimitiveRow {
  /** A stable slug — `eye-size`, `leg-adopt`. Never renamed: it is what carries his verdict. */
  id: string
  /** One of `PRIMITIVE_GROUPS`. */
  group?: string
  /** Plain English. "How big an eye is". */
  title?: string
  /** The ONE thing he is being asked to accept, as a question. */
  question?: string
  /** The measured value in the Kenney pack. */
  packSays?: string
  /** What the kits do today. */
  kitSays?: string
  /** The discrepancy, in one line. */
  gap?: string
  /** What we would change it to. */
  proposal?: string
  /** `file:line` provenance for every number above. */
  evidence?: string
  /** HIS. '' | 'ok' | 'reject'. Never written by an agent. */
  signoff?: string
  /** HIS. Never written by an agent. */
  note?: string
}

/** The only value that means "the kits may build out of this". */
export const signedOff = (row: { signoff: string }): boolean => row.signoff === SIGNED_OFF
/** He looked and said no. NOT the same as not having got to it. */
export const struck = (row: { signoff: string }): boolean => row.signoff === STRUCK

/* ------------------------------------------------------- the side-by-side --- */

/**
 * Which two real models stand beside each other for a row, and why those two.
 *
 * A number in a table is not a thing anyone can sign off on. The whole point of
 * this bench is that the pack's real geometry and the kit's real geometry are on
 * one turntable, at matched scale, so the gap the row describes in a sentence is
 * a gap he can see. `viewer.ts` loads the left side through the game's own pet
 * loader and builds the right side by calling the real `buildSpecies` — there is
 * no baked preview anywhere, for the reason `viewer.ts`'s header gives at
 * length: a preview is a copy, a copy drifts, and he would be signing off
 * something that is not what ships.
 */
export interface Comparison {
  /** An authored Kenney GLB, by species id. Loaded through the game's pet path. */
  packSpecies: string
  /**
   * Node names to lift out of that GLB. Empty means the whole animal.
   *
   * There are only nine node names across the pack's 133 mesh nodes and not one
   * of them is a head, an ear, a muzzle or an eye — so for the face rows this is
   * empty and MUST be, and that absence is itself half of what those rows say.
   */
  packParts: readonly string[]
  /** A species a kit BUILDS, constructed by the real `buildSpecies`. */
  kitSpecies: string
  /** Mesh names to lift out of the build. Empty means the whole animal. */
  kitParts: readonly string[]
  /** Printed beside the turntable: which side is which, and why this pair. */
  why: string
}

/**
 * The whole animal, both sides. What the face rows get, and not by choice.
 *
 * The pack fuses torso, head, ears, muzzle, nose, eyes, horns, antlers, mane and
 * shell into ONE `body` buffer per species, so there is no head node to lift and
 * no way to show a head on its own without triangle-range surgery. Standing the
 * two whole animals side by side at equal height is the honest picture, and it
 * is the picture the eye rows are about anyway: every one of their numbers is a
 * ratio against the animal's height.
 */
const WHOLE = (packSpecies: string, kitSpecies: string, why: string): Comparison =>
  ({ packSpecies, packParts: [], kitSpecies, kitParts: [], why })

/**
 * One comparison per group, and the compiler holds it exhaustive.
 *
 * `Record<PrimitiveGroup, …>` rather than a switch with a default, for the fault
 * `registry.ts packsFor` was written to close: three arms for four cases, and
 * the fourth silently inheriting the third's data. A group added to
 * `PRIMITIVE_GROUPS` without a comparison here is a compile error.
 */
const COMPARISON_BY_GROUP: Readonly<Record<PrimitiveGroup, Comparison>> = {
  /*
   * A pack fox against a kit hippo. The hippo is the big-eye end of the kit's
   * 2.95× spread, so the two extremes of the whole argument are in one frame.
   */
  Face: WHOLE('animal-fox', 'animal-badger',
    "LEFT is the pack — animal-fox, its face a flat cut-out sheet 0.0100 in front of the head. "
    + 'RIGHT is the kit — animal-badger, its eyes protruding spheres with separate pupils floating '
    + 'further forward still. Both scaled to exactly one unit tall, because every number on these '
    + "rows is a ratio against the animal's height."),

  /*
   * The same two whole animals, for the same reason: an edge is everywhere on a
   * model and nowhere in particular, so the silhouette IS the comparison. What
   * this pair shows is the 45° chamfer against the kit's perfectly sharp box,
   * and the smooth-shaded normals against the flat-shaded ones.
   */
  Edges: WHOLE('animal-fox', 'animal-badger',
    'LEFT is the pack — animal-fox. Every corner on it is either a single flat 45° cut or a '
    + 'two-step round-over, and every vertex normal is the area-weighted average of the faces '
    + 'meeting it. RIGHT is the kit — animal-badger, built from unit boxes scaled per part: '
    + 'perfectly sharp, twelve triangles a box. Both scaled to one unit tall.'),

  /*
   * THE BEST PICTURE ON THE BENCH, and the cheapest to build, because it is the
   * one place the pack ships a separable named node: `leg-front-left` is a real
   * mesh in every one of the 23 four-legged GLBs, and the kits happen to name
   * their own leg the same thing. So this is the same part, from both sides, at
   * the same scale — nothing is being approximated by the viewer either.
   */
  Limbs: {
    packSpecies: 'animal-fox',
    packParts: ['leg-front-left'],
    kitSpecies: 'animal-vole',
    kitParts: ['leg-front-left', 'paw-front-left'],
    why: "LEFT is the pack's real leg — the `leg-front-left` node lifted straight out of "
      + 'animal-fox.glb, a tapered octagonal frustum, 24 welded vertex positions, the same buffer '
      + 're-exported 86 times across the pack. RIGHT is the kit\'s leg for animal-hyena: a box '
      + 'and a paw box. Each animal was scaled to one unit tall BEFORE its leg was lifted, so '
      + "what you are comparing is how big a leg is relative to its own animal — which is what "
      + 'Joe pointed at.',
  },
}

/**
 * Rows that want their own pair rather than their group's.
 *
 * Not an else and not a fallback in disguise: every group above has an arm, so
 * nothing here is covering a hole. This is only for the rows whose argument is
 * about a DIFFERENT pair of animals than the rest of their group's — the
 * side-facing songbird eye, the quail's collisions, the body that stays
 * procedural. `comparisonFor` prefers this and a test asserts every shipped row
 * resolves to something.
 */
const COMPARISON_BY_ROW: Readonly<Record<string, Comparison>> = {
  /* The songbird half of the relief question: 13 of the 72 wear their eyes on
   * the ±X faces of the head, and no original does — all 63 decals face +Z. */
  'eye-relief': WHOLE('animal-fox', 'animal-mole',
    'LEFT is the pack — animal-fox, whose face is a flat sheet facing +Z, as all 63 decals in the '
    + 'pack do. RIGHT is the kit — animal-goose, a songbird: its eyes are on the SIDES of the '
    + 'head. Orbit round to the front of each. Both scaled to one unit tall.'),

  /* The collisions are on the quail specifically — an `eye-stripe` through the
   * eye's bounding box, and the eye intersecting the body itself. */
  'eye-collisions': WHOLE('animal-fox', 'animal-shrew',
    'LEFT is the pack — animal-fox: nothing overlaps a decal, it is a clean sheet on a clean '
    + 'plate. RIGHT is the kit — animal-quail, which carries an `eye-stripe` through the eye and '
    + 'an eye that intersects the body. Both scaled to one unit tall.'),

  /* The row that is a NO. The picture has to be the two BODIES, because the
   * claim is that this is the part where approximating is correct. */
  'body-stays-procedural': WHOLE('animal-fox', 'animal-vole',
    "LEFT is the pack — animal-fox, whose `body` node is a sculpted shell of 190–418 triangles "
    + 'with the head, ears, muzzle, nose, eyes and everything else fused into it. RIGHT is the '
    + 'kit — animal-hyena, whose body and head are boxes. There are 24 distinct faces in the '
    + 'whole pack and the roster wants 296 species, which is the argument for leaving this one '
    + 'alone. Both scaled to one unit tall.'),
}

/**
 * The two models a row stands on the turntable, or null if this build has no
 * pair for it.
 *
 * Null rather than a guess. A row whose group this build has never heard of is a
 * real state — the file is written by agents and lands ahead of the viewer that
 * renders it — and showing it the Face pair would be a confident lie about what
 * he is looking at.
 */
export const comparisonFor = (row: { id: string; group: string }): Comparison | null =>
  COMPARISON_BY_ROW[row.id] ?? (isGroup(row.group) ? COMPARISON_BY_GROUP[row.group] : null)

/** Every distinct comparison this build can render. For the validity test. */
export const allComparisons = (): Comparison[] =>
  [...Object.values(COMPARISON_BY_GROUP), ...Object.values(COMPARISON_BY_ROW)]

/* --------------------------------------------------------------- the join --- */

/** One primitive decision, everything about it in one place. */
export interface Primitive {
  id: string
  /** What the file said. Kept verbatim even when this build does not know it. */
  group: string
  /** True when `group` is one of `PRIMITIVE_GROUPS` and has a place in the order. */
  known: boolean
  title: string
  question: string
  packSays: string
  kitSays: string
  gap: string
  proposal: string
  evidence: string
  /** HIS. '' | 'ok' | 'reject'. */
  signoff: string
  /** HIS. */
  note: string
  /** Neither '', 'ok' nor 'reject' — a value nothing here will treat as a tick. */
  odd: boolean
  /** The pair of real models this row puts side by side, or null. */
  compare: Comparison | null
}

const str = (v: unknown): string => (typeof v === 'string' ? v.trim() : '')

/**
 * The rows, in the order he reads them: group order, then the FILE's own order
 * inside a group.
 *
 * Never sorted by title, and never by whether a row is signed off. `built.ts`
 * has the same rule for the same reason, learned on the name audit: he is
 * working down a list, and a row that moves under the cursor the moment he ticks
 * it takes his place with it. A group this build does not know sorts last, as a
 * visible bucket of its own, because hiding it would make the progress count a
 * lie about how much is left.
 */
export function primitivesBench(rows: readonly PrimitiveRow[]): Primitive[] {
  const rank = (group: string): number => {
    const at = (PRIMITIVE_GROUPS as readonly string[]).indexOf(group)
    return at === -1 ? PRIMITIVE_GROUPS.length : at
  }

  return rows
    .filter(r => str(r?.id) !== '')
    .map((r, i): Primitive & { at: number } => {
      const group = str(r.group)
      const signoff = str(r.signoff)
      const base = {
        id: str(r.id),
        group,
        known: isGroup(group),
        title: str(r.title),
        question: str(r.question),
        packSays: str(r.packSays),
        kitSays: str(r.kitSays),
        gap: str(r.gap),
        proposal: str(r.proposal),
        evidence: str(r.evidence),
        signoff,
        note: str(r.note),
        /* '' is not-yet-judged and is not odd. Anything that is not one of the
         * three known states is, and is counted rather than coerced. */
        odd: signoff !== '' && signoff !== SIGNED_OFF && signoff !== STRUCK,
        at: i,
      }
      return { ...base, compare: comparisonFor(base) }
    })
    .sort((a, b) => rank(a.group) - rank(b.group) || a.at - b.at)
    .map(({ at: _at, ...row }) => row)
}

/** How far he has got. The numbers always describe the WHOLE bench. */
export interface PrimitiveProgress {
  done: number
  /** Looked at and refused. A real answer, and not the absence of one. */
  struck: number
  total: number
  /** Neither ticked nor struck — what is actually left to do. */
  left: number
  /**
   * Rows carrying a `signoff` that is none of the three known values.
   *
   * Shown, because the alternative is silence. A hand-edited file with
   * `signoff: "yes"` in it must not read as a tick and must not read as
   * untouched either; both would be a lie about what he has said.
   */
  odd: number
  /** Rows in a group this build has no heading or order for. */
  ungrouped: number
  /** Rows with no side-by-side, so there is nothing to look at while deciding. */
  withoutPicture: number
  /** What the bar says. "3 of 8 signed off". */
  label: string
}

export function primitivesProgress(bench: readonly Primitive[]): PrimitiveProgress {
  const total = bench.length
  const done = bench.filter(signedOff).length
  const no = bench.filter(struck).length
  return {
    done,
    struck: no,
    total,
    left: total - done - no,
    odd: bench.filter(p => p.odd).length,
    ungrouped: bench.filter(p => !p.known).length,
    withoutPicture: bench.filter(p => p.compare === null).length,
    label: `${done} of ${total} signed off`,
  }
}

/* ------------------------------------------------------- the regeneration --- */

/**
 * A freshly measured row set, carrying across everything Joe has said.
 *
 * The contract, and the reason it is a named function rather than a habit: every
 * field but two is re-measured whenever anyone goes and measures the pack again,
 * and the file is rewritten wholesale when they do. If that rewrite can drop a
 * verdict, the sign-off is work a build step can destroy, and he will rightly
 * never trust the surface again.
 *
 * Two rules, both taken from `merge.mjs` so the two paths cannot disagree:
 *
 *   OWN   `signoff` and `note` come off the EXISTING row, by `id`, always. The
 *         fresh row's copies are ignored even when non-empty, because an agent
 *         has no business having an opinion about either and a non-empty one in
 *         a generated row is a bug, not an instruction.
 *   KEEP  an existing row the fresh set has never heard of survives, appended.
 *         A primitive that has stopped being measured has not stopped having
 *         been judged, and `mergeWhole` would keep it anyway — these two must
 *         agree or the answer depends on which route the writer took.
 */
export function regenerate(
  fresh: readonly PrimitiveRow[], existing: readonly PrimitiveRow[],
): PrimitiveRow[] {
  const his = new Map(existing.filter(r => str(r?.id) !== '').map(r => [str(r.id), r]))
  const seen = new Set<string>()

  const out = fresh.map((row): PrimitiveRow => {
    const id = str(row.id)
    seen.add(id)
    const was = his.get(id)
    return { ...row, signoff: str(was?.signoff), note: str(was?.note) }
  })

  for (const [id, row] of his) if (!seen.has(id)) out.push(row)
  return out
}

/* ---------------------------------------------------------- what is real --- */

/**
 * The two id spaces a comparison names, for the test that pins them.
 *
 * Exported rather than inlined into the test because the point is that they come
 * from the game's own tables: `SPECIES` is what `pets.ts` deals GLBs from, and
 * `SHIPPED_SPECIES` with a `build` is what a kit constructs. A typo in a
 * comparison is otherwise a blank turntable at his review hour, which is exactly
 * the failure this whole file is built to avoid.
 */
export const PACK_IDS: readonly string[] = SPECIES
export const KIT_IDS: readonly string[] =
  SHIPPED_SPECIES.filter(s => s.build !== undefined).map(s => s.id)
