import { describe, it, expect } from 'vitest'

/*
 * The emitter is plain ESM with no build step and no declarations, and
 * `tsconfig.json` does not turn on `allowJs`, so importing it from a `.ts` test
 * is an implicit `any` that `tsc --noEmit` refuses. Suppressed at the import
 * rather than papered over with a hand-written `.d.mts`, which would be a second
 * description of this module that could quietly stop matching it.
 */
// @ts-expect-error — see above; `emit.mjs` ships no types.
import { emitWords } from '../../tools/words/emit.mjs'

const row = (word: string, rung: number, verdict: string) =>
  ({ word, rung, verdict, replacement: '', note: '' })

describe('the words emitter', () => {
  it('emits only approved rows', () => {
    const out = emitWords({ words: [
      row('sun', 3, 'yes'),
      row('pig', 3, ''),
      row('cog', 3, 'no'),
    ] })
    expect(out).toContain('"sun"')
    expect(out, 'an unvetted word must be invisible').not.toContain('"pig"')
    expect(out, 'a rejected word must be invisible').not.toContain('"cog"')
  })

  it('uses the replacement when one is given', () => {
    const out = emitWords({ words: [
      { word: 'cog', rung: 3, verdict: 'replace', replacement: 'dog', note: '' },
    ] })
    expect(out).toContain('"dog"')
    expect(out).not.toContain('"cog"')
  })

  it('groups by rung id and keeps ledger order inside a rung', () => {
    const out = emitWords({ words: [
      row('sun', 3, 'yes'), row('fish', 4, 'yes'), row('cat', 3, 'yes'),
    ] })
    expect(out).toMatch(/3: \["sun", "cat"\]/)
    expect(out).toMatch(/4: \["fish"\]/)
  })

  it('emits an empty rung rather than omitting it', () => {
    const out = emitWords({ words: [row('sun', 3, '')] })
    expect(out).toMatch(/3: \[\]/)
  })

  it('ends every line with LF and never CRLF', () => {
    const out = emitWords({ words: [row('sun', 3, 'yes')] })
    expect(out).not.toContain('\r')
  })

  /*
   * emit.mjs:32 used to build the array with a hand-rolled `'${w}'` template —
   * fine for every word audited so far, and silently broken the moment a
   * replacement carries an apostrophe ("don't", "can't", "I'm"), all entirely
   * plausible at the higher rungs. The unescaped `'` closes the string early,
   * so `src/core/rung-words.ts` — a file Joe is told never to edit — comes out
   * syntactically invalid and the whole app stops building, from a legitimate
   * approval in his own review box. `JSON.stringify` is the fix; this proves
   * the OUTPUT actually parses as TypeScript, not just that the word survived
   * as a substring.
   */
  it('escapes an apostrophe so the emitted module stays valid TypeScript', () => {
    const out = emitWords({ words: [row("don't", 3, 'yes')] })
    expect(out).toContain(JSON.stringify("don't"))

    /*
     * `typescript@7` here ships only the native `tsc` CLI (no programmatic
     * `transpileModule`), so this isolates the one line that is TypeScript
     * rather than plain JS — the type annotation on the export, which the
     * apostrophe bug never touched — and parses the rest as a function body.
     * An unescaped `'` inside the word breaks that parse exactly as it would
     * break `tsc` on the real file: a SyntaxError building the function, not
     * a value that happens to look wrong.
     */
    const asJs = out.replace(
      'export const RUNG_WORDS: Record<number, readonly string[]> =',
      'return',
    )
    let rungWords: Record<number, readonly string[]> = {}
    expect(() => { rungWords = new Function(asJs)() }).not.toThrow()
    expect(rungWords[3]).toContain("don't")
  })
})

/*
 * THE GUARD THAT PAYS FOR THE PRONOUN EXEMPTION.
 *
 * `tests/copy/pronouns.test.ts` skips `src/core/rung-words.ts` entirely, because
 * a reading ladder has to be able to teach "he has" and "she can" without that
 * counting as gendering the child. That exemption is only honest while the file
 * is what it claims to be: generated, and holding nothing but words Joe has
 * ruled on. These two tests are what make it so — if the file is ever
 * hand-edited, or a word appears in it that no approved row backs, the
 * exemption stops being a scope decision and starts being a hole, and CI says so.
 */
describe('the generated word module is exactly what Joe approved', () => {
  const read = (p: string): string =>
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    (require('node:fs') as typeof import('node:fs')).readFileSync(p, 'utf8')

  it('still declares itself generated, so nobody hand-edits it', () => {
    expect(read('src/core/rung-words.ts')).toContain('GENERATED by `npm run words:emit`')
  })

  it('contains no word that Joe has not approved', () => {
    const ledger = JSON.parse(read('joe/words-audit.json')) as {
      words: Array<{ word: string; verdict: string; replacement: string }>
    }
    const approved = new Set(
      ledger.words
        .filter(r => ['yes', 'replace'].includes(String(r.verdict ?? '').trim().toLowerCase()))
        .map(r => (String(r.replacement ?? '').trim() || String(r.word ?? '').trim())),
    )
    const emitted = [...read('src/core/rung-words.ts').matchAll(/"([^"]+)"/g)].map(m => m[1]!)
    expect(emitted.length, 'no words emitted at all — has words:emit been run?').toBeGreaterThan(0)
    expect(emitted.filter(w => !approved.has(w))).toEqual([])
  })
})
