/**
 * The words ledger -> the generated module.
 *
 * ONE RULE, and it is the whole point of this file: a row with no verdict is
 * NOT emitted. Unvetted means invisible, exactly as `pool.ts` treats a species
 * nobody has signed off, and it is what makes it safe for an agent to draft two
 * hundred words in bulk. There is deliberately no "pending" state that deals.
 */
import { readFileSync, writeFileSync } from 'node:fs'

const APPROVED = new Set(['yes', 'replace'])

/** The words a row contributes: its replacement if it has one, else itself. */
function wordOf(row) {
  const v = String(row.verdict ?? '').trim().toLowerCase()
  if (!APPROVED.has(v)) return null
  const rep = String(row.replacement ?? '').trim()
  return rep || String(row.word ?? '').trim() || null
}

export function emitWords(ledger) {
  const rows = ledger?.words ?? []
  const rungs = new Map()
  for (const r of rows) {
    const rung = Number(r.rung)
    if (!Number.isInteger(rung)) continue
    if (!rungs.has(rung)) rungs.set(rung, [])
    const w = wordOf(r)
    if (w) rungs.get(rung).push(w)
  }
  /*
   * `JSON.stringify(w)`, not a hand-rolled `'${w}'` template — a replacement
   * containing an apostrophe ("don't", "can't", "I'm") is entirely plausible
   * at the higher rungs, and the old template closed the string early on it,
   * producing a `src/core/rung-words.ts` that failed to even parse. This
   * escapes whatever the word actually contains, the way any code emitting a
   * string literal should.
   */
  const body = [...rungs.keys()].sort((a, b) => a - b)
    .map(k => `  ${k}: [${rungs.get(k).map(w => JSON.stringify(w)).join(', ')}],`)
    .join('\n')
  return [
    '/**',
    ' * GENERATED by `npm run words:emit` from `joe/words-audit.json`. Do not edit.',
    ' *',
    ' * Only APPROVED rows appear here. A word Joe has not ruled on is absent, so a',
    ' * rung whose list is half-approved deals only the approved half.',
    ' */',
    'export const RUNG_WORDS: Record<number, readonly string[]> = {',
    body,
    '}',
    '',
  ].join('\n')
}

export function emitToDisk(ledgerPath, outPath) {
  const ledger = JSON.parse(readFileSync(ledgerPath, 'utf8'))
  writeFileSync(outPath, emitWords(ledger), 'utf8')
}
