/**
 * One lesson, one file, read and written by both a human and this tool.
 *
 * `joe/lessons/<id>.md` is a text file first and a data structure second. Joe
 * edits it in the workbench or in an editor, whichever is to hand, and neither
 * may lose the other's work — so the format is front-matter plus two named
 * sections, and the writer round-trips exactly what the reader parses.
 *
 * The front-matter is a deliberately stupid subset of YAML: `key: value`, one
 * per line, no nesting, no lists. Enough for six fields, and no dependency.
 */
import { readText, writeText, listDir } from './repo.mjs'

export const LESSON_DIR = 'joe/lessons'

/** The statuses a lesson passes through. `draft` means "awaiting the red pen". */
export const STATUSES = ['draft', 'vetted']

const FIELDS = ['id', 'title', 'exemplar', 'file', 'status', 'approxSeconds', 'requires']

export function parseLesson(raw, id) {
  const meta = { id, title: '', exemplar: '', file: '', status: 'draft', approxSeconds: 0, requires: '' }
  let body = raw

  const fm = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(raw)
  if (fm) {
    body = raw.slice(fm[0].length)
    for (const line of fm[1].split(/\r?\n/)) {
      const m = /^([A-Za-z]+):\s*(.*)$/.exec(line)
      if (m && FIELDS.includes(m[1])) meta[m[1]] = m[2].trim()
    }
  }
  meta.approxSeconds = Number(meta.approxSeconds) || 0

  /*
   * Find the heading, then take everything up to the next one.
   *
   * Written as one regex first, terminated with `\Z` — which JavaScript does
   * not have and treats as a literal Z, so the LAST section of every file
   * (always the script, the part that matters) silently parsed as empty. Two
   * steps, no lookahead, nothing to get subtly wrong.
   */
  const section = name => {
    const head = new RegExp(`^##\\s+${name}\\s*$`, 'mi').exec(body)
    if (!head) return ''
    const rest = body.slice(head.index + head[0].length)
    const next = /^##\s/m.exec(rest)
    return (next ? rest.slice(0, next.index) : rest).trim()
  }

  return { ...meta, beats: section('Visual beats'), script: section('Script') }
}

export function formatLesson(l) {
  const fm = FIELDS.map(k => `${k}: ${l[k] ?? ''}`).join('\n')
  return `---\n${fm}\n---\n\n## Visual beats\n\n${(l.beats || '').trim()}\n\n## Script\n\n${(l.script || '').trim()}\n`
}

export function loadLesson(root, id) {
  const raw = readText(root, `${LESSON_DIR}/${id}.md`)
  return raw === null ? null : parseLesson(raw, id)
}

export const saveLesson = (root, l) =>
  writeText(root, `${LESSON_DIR}/${l.id}.md`, formatLesson(l))

/**
 * Every lesson, in ladder order.
 *
 * Order is a curriculum fact, not an alphabetical one — INTRO-TEN comes first
 * because it is the debut, and the ADD ladder before the SUB ladder because
 * that is how the boxes are ordered. Anything unrecognised sorts to the end
 * rather than being dropped, so a lesson Joe invents by hand still appears.
 */
const RANK = ['INTRO-TEN', 'L-ADD-1', 'L-ADD-2', 'L-ADD-3', 'L-ADD-4', 'L-ADD-5',
  'L-SUB-1', 'L-SUB-2', 'L-SUB-3', 'L-SUB-4']

export function allLessons(root) {
  const ids = listDir(root, LESSON_DIR).filter(f => f.endsWith('.md')).map(f => f.slice(0, -3))
  const rank = id => { const i = RANK.indexOf(id); return i === -1 ? RANK.length : i }
  ids.sort((a, b) => rank(a) - rank(b) || a.localeCompare(b))
  return ids.map(id => loadLesson(root, id)).filter(Boolean)
}

/**
 * The export the bake and the Run C lesson player both consume.
 *
 * Context brackets, not prose: the player wants `id`, `exemplar` and `file` as
 * attributes and the script as the element's text, and the bake wants exactly
 * the same string it will synthesize. One artefact, so the clip and the player
 * can never be reading two different scripts.
 */
export function exportPlan(lessons) {
  const head = [
    '# Fred\'s Little Lessons — the vetted plan',
    '',
    '*Generated by `npm run workbench` → Export. Do not hand-edit: the source of',
    'truth is `joe/lessons/<id>.md`, and the next export overwrites this file.*',
    '',
    'Laws that govern every lesson: Fred teaches the METHOD, never the live answer —',
    'every lesson runs on its FIXED exemplar, deliberately different from the question',
    'on screen, and always ends with the handover ("Now you try yours!").',
    '',
  ]
  const blocks = lessons.map(l => [
    `## ${l.id} — ${l.title}`,
    '',
    `*Status: ${l.status} · Exemplar: ${l.exemplar} · ~${l.approxSeconds}s${l.requires ? ` · Requires ${l.requires}` : ''}*`,
    '',
    '**Visual beats:** ' + (l.beats || '').replace(/\s*\n\s*/g, ' '),
    '',
    `<lesson id="${l.id}" exemplar="${esc(l.exemplar)}" file="${esc(l.file)}">${(l.script || '').trim()}</lesson>`,
    '',
  ].join('\n'))
  return head.concat(blocks).join('\n')
}

const esc = s => String(s ?? '').replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;')
