/**
 * GENERATED by `npm run words:emit` from `joe/words-audit.json`. Do not edit.
 *
 * Only APPROVED rows appear here. A word Joe has not ruled on is absent, so a
 * rung whose list is half-approved deals only the approved half.
 */
export const RUNG_WORDS: Record<number, readonly string[]> = {

}
